version: "3.8"

services:
    # Frontend React application
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - server
        networks:
            - app-network

    # Backend Node.js application
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
            - DATABASE_URL=mongodb://db:27017/dockercomposeTest
        depends_on:
            - db
        networks:
            - app-network

    # MongoDB database
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodb_data:
